# Generated by Django 2.0.9 on 2018-12-12 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.date(2018, 12, 12), null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='request',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='request',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='request',
            name='parent_email',
            field=models.CharField(max_length=200, null=True, verbose_name="Parent's Email"),
        ),
        migrations.AddField(
            model_name='request',
            name='roll',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.time(10, 56, 1, 32863), null=True, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='request',
            name='venue',
            field=models.CharField(blank=True, max_length=512, verbose_name='Venue'),
        ),
    ]
