# Generated by Django 2.0.9 on 2018-12-12 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20181212_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.time(12, 14, 22, 68789), null=True, verbose_name='Time'),
        ),
    ]
